spring:
  datasource:
    url: ${jdbcUrl} #jdbc:mariadb://crawling-server.c4y9vm1irfhh.ap-northeast-2.rds.amazonaws.com:3306/test
    username: ${username} #admin
    password: ${password} #adminadmin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail} #classmoa.corp@gmail.com
    password: ${gmailPassword} #vkxsuwlaoisqicrp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분