server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${jdbcUrl}
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${gmailPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  data:
    redis:
      port: 6379
      host: 43.201.31.162
      password: ${redisPassword}

jwt:
  secret: "classmoa"