spring:
  datasource:
    url: crawling-server.c4y9vm1irfhh.ap-northeast-2.rds.amazonaws.com
    username: admin
    password: adminadmin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true //println
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace